### ISSUE TITLE
tci function throws error

### ISSUE THREAD

**Issue by Andreas-Bio** [eberlejonas/TaxCI#1]
This line throws an "subscript out of bounds" error.
x[nrow(x) + 1, ] <- x[nrow(x), ]

(Had to rename the .tree to .pdf to upload. Do not open with Adobe Reder.)

```
library(ape);library(doSNOW);library(spider);library(TaxCI)
y <- read.tree(file="RAxML_bipartitions.pdf")
lab <- y$tip.label
scilab <- gsub("^(.*?)_(.*?)_(.*?)$","\\1 \\2",lab)
genlab <- gsub("^(.*?)_(.*?)_(.*?)$","\\1",lab) 
scilab <- cbind(scilab,genlab)
rownames(scilab) <- lab


tcix <- tci (tree=y,x=scilab,level=1,num_cores=4)
```

[RAxML_bipartitions.pdf](https://github.com/eberlejonas/TaxCI/files/1072143/RAxML_bipartitions.pdf)

**Comment by eberlejonas** [comment]
Dear andzandz11,
thanks for pointing out this issue. I'll implement a check for this in the next version. `x` needs to be a data.frame. Try the following modification of your code and it will run:
```{r}
library(TaxCI)
y <- read.tree(file="RAxML_bipartitions.pdf")
lab <- y$tip.label
scilab <- gsub("^(.*?)_(.*?)_(.*?)$","\\1 \\2",lab)
genlab <- gsub("^(.*?)_(.*?)_(.*?)$","\\1",lab) 
scilab <- data.frame(scilab,genlab)
rownames(scilab) <- lab
tcix <- tci(tree=y,x=scilab,level=1,num_cores=4)
```
Jonas

**Comment by eberlejonas** [comment]
Dear andzandz11,
thanks for pointing out this issue. I'll implement a check for this in the next version. `x` needs to be a data.frame. Try the following modification of your code and it will run:
```R
library(TaxCI)
y <- read.tree(file="RAxML_bipartitions.pdf")
lab <- y$tip.label
scilab <- gsub("^(.*?)_(.*?)_(.*?)$","\\1 \\2",lab)
genlab <- gsub("^(.*?)_(.*?)_(.*?)$","\\1",lab) 
scilab <- data.frame(scilab,genlab)
rownames(scilab) <- lab
tcix <- tci(tree=y,x=scilab,level=1,num_cores=4)
```
Jonas
